using System.Collections.Concurrent;
using System.Text;

namespace Nice3point.Revit.Toolkit.SourceGenerators;

/// <summary>
///     Implementation of ICodeWriter for generating formatted C# source code.
///     Automatically handles indentation and newlines based on code structure.
/// </summary>
internal sealed class CodeWriter : ICodeWriter
{
    private static readonly ConcurrentDictionary<string, string> IndentCache = new();
    private readonly StringBuilder _builder = new();
    private readonly string _indentString;
    private bool _isNewLine = true;

    public CodeWriter(string indentString = "    ")
    {
        _indentString = indentString;

        _builder.AppendLine("// <auto-generated/>");
        _builder.AppendLine("#pragma warning disable");
        _builder.AppendLine("#nullable enable");
        _builder.AppendLine();
    }

    public int IndentLevel { get; private set; }

    /// <summary>
    ///     Sets the initial indentation level. Useful for inline code generation.
    /// </summary>
    public ICodeWriter SetIndentLevel(int level)
    {
        IndentLevel = Math.Max(0, level);
        return this;
    }

    /// <summary>
    ///     Appends text to the current line, applying indentation if at the start of a new line.
    /// </summary>
    public ICodeWriter Append(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return this;
        }

        if (_isNewLine)
        {
            _builder.Append(GetIndentation(IndentLevel));
            _isNewLine = false;
        }

        _builder.Append(text);
        return this;
    }

    /// <summary>
    ///     Appends a line of text with proper indentation.
    ///     When called without arguments or with an empty string, emits a blank line.
    /// </summary>
    public ICodeWriter AppendLine(string text = "")
    {
        if (string.IsNullOrEmpty(text))
        {
            _builder.AppendLine();
        }
        else
        {
            if (_isNewLine)
            {
                _builder.Append(GetIndentation(IndentLevel));
            }

            _builder.AppendLine(text);
        }

        _isNewLine = true;
        return this;
    }

    /// <summary>
    ///     Appends multiple lines of code.
    /// </summary>
    public ICodeWriter AppendLines(IEnumerable<string> lines)
    {
        foreach (var line in lines)
        {
            AppendLine(line);
        }

        return this;
    }

    /// <summary>
    ///     Increases the indentation level.
    /// </summary>
    public ICodeWriter Indent()
    {
        IndentLevel++;
        return this;
    }

    /// <summary>
    ///     Decreases the indentation level.
    /// </summary>
    public ICodeWriter Unindent()
    {
        if (IndentLevel > 0)
        {
            IndentLevel--;
        }

        return this;
    }

    /// <summary>
    ///     Begins a code block with automatic formatting, handling opening brace and indentation.
    ///     Returns an IDisposable that will unindent and append closing brace when disposed.
    /// </summary>
    public IDisposable BeginBlock(string leadingText = "")
    {
        if (!string.IsNullOrEmpty(leadingText))
        {
            AppendLine(leadingText);
        }

        AppendLine("{");
        Indent();

        return new IndentScope(this);
    }

    /// <summary>
    ///     Appends a code block with automatic braces and indentation.
    /// </summary>
    public ICodeWriter AppendBlock(string header, Action<ICodeWriter> body)
    {
        using (BeginBlock(header))
        {
            body(this);
        }

        return this;
    }

    /// <summary>
    ///     Conditionally appends a line.
    /// </summary>
    public ICodeWriter AppendLineIf(bool condition, string line)
    {
        if (condition)
        {
            AppendLine(line);
        }

        return this;
    }

    /// <summary>
    ///     Gets the generated code as a string.
    /// </summary>
    public override string ToString()
    {
        return _builder.ToString();
    }

    /// <summary>
    ///     Clears the internal buffer.
    /// </summary>
    public void Dispose()
    {
        _builder.Clear();
    }

    /// <summary>
    ///     Gets the cached indentation string for the specified level, building it if necessary.
    /// </summary>
    private string GetIndentation(int level)
    {
        var key = _indentString + ":" + level;
        if (IndentCache.TryGetValue(key, out var cached))
        {
            return cached;
        }

        var indentation = string.Concat(Enumerable.Repeat(_indentString, level));
        IndentCache.TryAdd(key, indentation);
        return indentation;
    }

    /// <summary>
    ///     Internal helper class to manage indentation scope using IDisposable.
    /// </summary>
    private sealed class IndentScope(CodeWriter writer) : IDisposable
    {
        private readonly CodeWriter _writer = writer ?? throw new ArgumentNullException(nameof(writer));
        private bool _disposed;

        public void Dispose()
        {
            if (!_disposed)
            {
                _writer.Unindent();
                _writer.AppendLine("}");
                _disposed = true;
            }
        }
    }
}
