<Project Sdk="Nice3point.Revit.Sdk/6.2.3">

    <PropertyGroup>
        <UseWpf>true</UseWpf>
        <DefineConstants>$(DefineConstants);JETBRAINS_ANNOTATIONS</DefineConstants>
        <Configurations>Debug.R20;Debug.R21;Debug.R22;Debug.R23;Debug.R24;Debug.R25;Debug.R26;Debug.R27</Configurations>
        <Configurations>$(Configurations);Release.R20;Release.R21;Release.R22;Release.R23;Release.R24;Release.R25;Release.R26;Release.R27</Configurations>
    </PropertyGroup>

    <PropertyGroup>
        <PackageType>Dependency</PackageType>
        <PackageId>Nice3point.Revit.Toolkit</PackageId>
        <Authors>Nice3point</Authors>
        <Description>Toolkit for Revit plugin development</Description>
        <PackageTags>autodesk;revit;api;toolkit</PackageTags>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/Nice3point/RevitToolkit</RepositoryUrl>
        <PackageProjectUrl>https://github.com/Nice3point/RevitToolkit</PackageProjectUrl>
        <PackageIcon>images\PackageIcon.png</PackageIcon>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <DebugType>portable</DebugType>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" PrivateAssets="all"/>
        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <!-- Build order references -->
        <ProjectReference Include="..\Nice3point.Revit.Toolkit.Analyzers\Nice3point.Revit.Toolkit.Analyzers.csproj" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Nice3point.Revit.Toolkit.Analyzers.Roslyn414\Nice3point.Revit.Toolkit.Analyzers.Roslyn414.csproj" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Nice3point.Revit.Toolkit.Analyzers.CodeFixers\Nice3point.Revit.Toolkit.Analyzers.CodeFixers.csproj" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Nice3point.Revit.Toolkit.Analyzers.CodeFixers.Roslyn414\Nice3point.Revit.Toolkit.Analyzers.CodeFixers.Roslyn414.csproj" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Nice3point.Revit.Toolkit.SourceGenerators\Nice3point.Revit.Toolkit.SourceGenerators.csproj" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Nice3point.Revit.Toolkit.SourceGenerators.Roslyn414\Nice3point.Revit.Toolkit.SourceGenerators.Roslyn414.csproj" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md" PackagePath="" Pack="true" Visible="false"/>
        <None Include="..\..\LICENSE.md" PackagePath="" Pack="true" Visible="false"/>
        <None Include="..\..\.nuget\PackageIcon.png" PackagePath="images/" Pack="true" Visible="false"/>
        <None Include="..\Nice3point.Revit.Toolkit.SourceGenerators\bin\$(Configuration)\netstandard2.0\Nice3point.Revit.Toolkit.SourceGenerators.dll" PackagePath="analyzers\dotnet\roslyn5.0\cs" Pack="true" Visible="false"/>
        <None Include="..\Nice3point.Revit.Toolkit.SourceGenerators.Roslyn414\bin\$(Configuration)\netstandard2.0\Nice3point.Revit.Toolkit.SourceGenerators.dll" PackagePath="analyzers\dotnet\roslyn4.14\cs" Pack="true" Visible="false"/>
        <None Include="..\Nice3point.Revit.Toolkit.Analyzers\bin\$(Configuration)\netstandard2.0\Nice3point.Revit.Toolkit.Analyzers.dll" PackagePath="analyzers\dotnet\roslyn5.0\cs" Pack="true" Visible="false"/>
        <None Include="..\Nice3point.Revit.Toolkit.Analyzers.Roslyn414\bin\$(Configuration)\netstandard2.0\Nice3point.Revit.Toolkit.Analyzers.dll" PackagePath="analyzers\dotnet\roslyn4.14\cs" Pack="true" Visible="false"/>
        <None Include="..\Nice3point.Revit.Toolkit.Analyzers.CodeFixers\bin\$(Configuration)\netstandard2.0\Nice3point.Revit.Toolkit.Analyzers.CodeFixers.dll" PackagePath="analyzers\dotnet\roslyn5.0\cs" Pack="true" Visible="false"/>
        <None Include="..\Nice3point.Revit.Toolkit.Analyzers.CodeFixers.Roslyn414\bin\$(Configuration)\netstandard2.0\Nice3point.Revit.Toolkit.Analyzers.CodeFixers.dll" PackagePath="analyzers\dotnet\roslyn4.14\cs" Pack="true" Visible="false"/>
    </ItemGroup>

</Project>