<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\Directory.Roslyn.props"/>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="AnalyzerReleases.Shipped.md"/>
        <AdditionalFiles Include="AnalyzerReleases.Unshipped.md"/>
    </ItemGroup>

</Project>