<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="Nice3point.Revit.Toolkit.SourceGenerators.props" />
    
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    </ItemGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="Nice3point.Revit.Toolkit.SourceGenerators.Tests" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
        <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    </ItemGroup>

</Project>
