<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <EnableTUnitPolyfills>false</EnableTUnitPolyfills>
        <NoWarn>$(NoWarn);RS2008</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\source\Nice3point.Revit.Toolkit.SourceGenerators\Nice3point.Revit.Toolkit.SourceGenerators.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\source\Nice3point.Revit.Toolkit.Analyzers\Diagnostics\DiagnosticDescriptors.cs"
                 Link="Diagnostics\DiagnosticDescriptors.cs" />
    </ItemGroup>

</Project>
