using Microsoft.CodeAnalysis.Testing;
using Nice3point.Revit.Toolkit.Analyzers.ExternalEvents;
using AnalyzerTest = Nice3point.Revit.Toolkit.Analyzers.CodeFixers.Tests.Verifiers.AnalyzerTest<
    Nice3point.Revit.Toolkit.Analyzers.AsyncVoidMethodAnalyzer>;

namespace Nice3point.Revit.Toolkit.Analyzers.CodeFixers.Tests;

public sealed class AsyncVoidMethodAnalyzerTests
{
    [Test]
    public async Task AsyncVoidMethod_ReportsDiagnosticAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       using Nice3point.Revit.Toolkit.External;

                       public partial class Model
                       {
                           [ExternalEvent]
                           private async void {|#0:Run|}() => await System.Threading.Tasks.Task.Yield();
                       }
                       """
        };

        test.ExpectedDiagnostics.Add(new DiagnosticResult(ExternalEventDiagnostics.AsyncVoidMethod)
            .WithLocation(0)
            .WithArguments("Run"));

        await test.RunAsync();
    }

    [Test]
    [Arguments("[ExternalEvent] private void Run() { }")]
    [Arguments("[ExternalEvent] private async System.Threading.Tasks.Task RunAsync() { await System.Threading.Tasks.Task.Yield(); }")]
    [Arguments("[ExternalEvent] private async System.Threading.Tasks.Task<int> RunAsync() { await System.Threading.Tasks.Task.Yield(); return 1; }")]
    [Arguments("private async void Run() { await System.Threading.Tasks.Task.Yield(); }")]
    public async Task NonTargetMethod_ReportsNothingAsync(string method)
    {
        var test = new AnalyzerTest
        {
            TestCode = $$"""
                         using Nice3point.Revit.Toolkit.External;

                         public partial class Model
                         {
                             {{method}}
                         }
                         """
        };

        await test.RunAsync();
    }

    [Test]
    public async Task UnrelatedAttribute_ReportsNothingAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       public sealed class ExternalEventAttribute : System.Attribute;

                       public partial class Model
                       {
                           [ExternalEvent]
                           private async void Run() { await System.Threading.Tasks.Task.Yield(); }
                       }
                       """
        };

        await test.RunAsync();
    }

    [Test]
    public async Task MissingAttributeType_ReportsNothingAsync()
    {
        var test = new AnalyzerTest();
        test.TestState.Sources.Clear();
        test.TestCode = """
                        public class Model
                        {
                            private async void Run() { await System.Threading.Tasks.Task.Yield(); }
                        }
                        """;

        await test.RunAsync();
    }

    [Test]
    public async Task GeneratedCode_ReportsNothingAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       // <auto-generated/>
                       using Nice3point.Revit.Toolkit.External;

                       public partial class Model
                       {
                           [ExternalEvent]
                           private async void Run() { await System.Threading.Tasks.Task.Yield(); }
                       }
                       """
        };

        await test.RunAsync();
    }

    [Test]
    public async Task MultipleAttributedMethods_ReportsEachMethodAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       using Nice3point.Revit.Toolkit.External;

                       public partial class Model
                       {
                           [ExternalEvent]
                           private async void {|#0:First|}() { }

                           [ExternalEvent]
                           private async void {|#1:Second|}() { }
                       }
                       """
        };

        test.ExpectedDiagnostics.AddRange([
            new DiagnosticResult(ExternalEventDiagnostics.AsyncVoidMethod).WithLocation(0).WithArguments("First"),
            new DiagnosticResult(ExternalEventDiagnostics.AsyncVoidMethod).WithLocation(1).WithArguments("Second")
        ]);

        await test.RunAsync();
    }
}
