using Microsoft.CodeAnalysis.Testing;
using Nice3point.Revit.Toolkit.Analyzers.ExternalEvents;
using AnalyzerTest = Nice3point.Revit.Toolkit.Analyzers.CodeFixers.Tests.Verifiers.AnalyzerTest<
    Nice3point.Revit.Toolkit.Analyzers.ExternalEventContainingTypeNotPartialAnalyzer>;

namespace Nice3point.Revit.Toolkit.Analyzers.CodeFixers.Tests;

public sealed class ContainingTypeNotPartialAnalyzerTests
{
    [Test]
    [Arguments("public partial class Model { [ExternalEvent] private void Run() { } }")]
    [Arguments("public class Model { private void Run() { } }")]
    [Arguments("public partial class Outer { public partial class Inner { [ExternalEvent] private void Run() { } } }")]
    public async Task ValidContainingType_ReportsNothingAsync(string declaration)
    {
        var test = new AnalyzerTest
        {
            TestCode = $"""
                        using Nice3point.Revit.Toolkit.External;

                        {declaration}
                        """
        };

        await test.RunAsync();
    }

    [Test]
    public async Task UnrelatedAttribute_ReportsNothingAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       public sealed class ExternalEventAttribute : System.Attribute;

                       public class Model
                       {
                           [ExternalEvent]
                           private void Run() { }
                       }
                       """
        };

        await test.RunAsync();
    }

    [Test]
    public async Task MissingAttributeType_ReportsNothingAsync()
    {
        var test = new AnalyzerTest();
        test.TestState.Sources.Clear();
        test.TestCode = "public class Model { private void Run() { } }";
        await test.RunAsync();
    }

    [Test]
    public async Task GeneratedCode_ReportsNothingAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       // <auto-generated/>
                       using Nice3point.Revit.Toolkit.External;

                       public class Model
                       {
                           [ExternalEvent]
                           private void Run() { }
                       }
                       """
        };

        await test.RunAsync();
    }

    [Test]
    public async Task PartialTypeAcrossFiles_ReportsNothingAsync()
    {
        var test = new AnalyzerTest();
        test.TestState.Sources.Add(("Model.cs",
            """
            public partial class Model<T> where T : class
            {
                public partial class Inner;
            }
            """));

        test.TestState.Sources.Add(("Model.Events.cs",
            """
            using Nice3point.Revit.Toolkit.External;

            public partial class Model<T>
            {
                public partial class Inner
                {
                    [ExternalEvent]
                    private void Run(T value) { }
                }
            }
            """));

        await test.RunAsync();
    }

    [Test]
    public async Task MultipleAttributedMethods_ReportsOneDiagnosticPerTypeAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       using Nice3point.Revit.Toolkit.External;

                       public class {|#0:Model|}
                       {
                           [ExternalEvent]
                           private void First() { }

                           [ExternalEvent]
                           private void Second() { }
                       }
                       """
        };

        test.ExpectedDiagnostics.Add(new DiagnosticResult(ExternalEventDiagnostics.ContainingTypeNotPartial)
            .WithLocation(0)
            .WithArguments("Model", "First"));

        await test.RunAsync();
    }

    [Test]
    public async Task NonPartialHierarchy_ReportsEachContainingTypeAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       using Nice3point.Revit.Toolkit.External;

                       public class {|#0:Outer|}
                       {
                           public class {|#1:Inner|}
                           {
                               [ExternalEvent]
                               private void Run() { }
                           }
                       }
                       """
        };

        test.ExpectedDiagnostics.AddRange([
            new DiagnosticResult(ExternalEventDiagnostics.ContainingTypeNotPartial).WithLocation(0).WithArguments("Outer", "Run"),
            new DiagnosticResult(ExternalEventDiagnostics.ContainingTypeNotPartial).WithLocation(1).WithArguments("Inner", "Run")
        ]);

        await test.RunAsync();
    }

    [Test]
    public async Task PartialOuterType_ReportsNonPartialInnerAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       using Nice3point.Revit.Toolkit.External;

                       public partial class Outer
                       {
                           public class {|#0:Inner|}
                           {
                               [ExternalEvent]
                               private void Run() { }
                           }
                       }
                       """
        };

        test.ExpectedDiagnostics.Add(new DiagnosticResult(ExternalEventDiagnostics.ContainingTypeNotPartial)
            .WithLocation(0)
            .WithArguments("Inner", "Run"));

        await test.RunAsync();
    }

    [Test]
    public async Task PartialIntermediateType_ReportsNonPartialAncestorsAndDescendantsAsync()
    {
        var test = new AnalyzerTest
        {
            TestCode = """
                       using Nice3point.Revit.Toolkit.External;

                       public class {|#0:Outer|}
                       {
                           public partial class Middle
                           {
                               public class {|#1:Inner|}
                               {
                                   [ExternalEvent]
                                   private void Run() { }
                               }
                           }
                       }
                       """
        };

        test.ExpectedDiagnostics.AddRange([
            new DiagnosticResult(ExternalEventDiagnostics.ContainingTypeNotPartial).WithLocation(0).WithArguments("Outer", "Run"),
            new DiagnosticResult(ExternalEventDiagnostics.ContainingTypeNotPartial).WithLocation(1).WithArguments("Inner", "Run")
        ]);

        await test.RunAsync();
    }
}
