using System.Text;

namespace Nice3point.Revit.Toolkit.SourceGenerators.CSharp;

internal sealed class CodeWriter
{
    private readonly StringBuilder _builder = new();
    private int _indentLevel;

    public CodeWriter()
    {
        AppendLine("// <auto-generated/>");
        AppendLine("#pragma warning disable");
        AppendLine("#nullable enable");
        AppendLine();
    }

    public void AppendLine(string text = "")
    {
        if (!string.IsNullOrEmpty(text))
        {
            _builder.Append(' ', _indentLevel * 4);
        }

        _builder.AppendLine(text);
    }

    public IDisposable BeginBlock(string leadingText, string closingText = "}")
    {
        AppendLine(leadingText);
        AppendLine("{");
        _indentLevel++;
        return new BlockScope(this, closingText);
    }

    public override string ToString()
    {
        return _builder.ToString();
    }

    private sealed class BlockScope(CodeWriter writer, string closingText) : IDisposable
    {
        private bool _disposed;

        public void Dispose()
        {
            if (_disposed)
            {
                return;
            }

            writer._indentLevel--;
            writer.AppendLine(closingText);
            _disposed = true;
        }
    }
}
