//HintName: Consumer.Model.event.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Model
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IExternalEvent<eventArgs> eventEvent => field ??= new global::Nice3point.Revit.Toolkit.External.ExternalEvent<eventArgs>((args) => @event(args.Quantity, args.Label));

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent<eventArgs> eventAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncExternalEvent<eventArgs>((args) => @event(args.Quantity, args.Label));

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public sealed record eventArgs(int Quantity, string Label);
    }

    public static partial class ModelExtensions
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public static global::Autodesk.Revit.UI.ExternalEventRequest Raise(this global::Nice3point.Revit.Toolkit.External.IExternalEvent<Model.eventArgs> externalEvent, int quantity, string label)
        {
            return externalEvent.Raise(new Model.eventArgs(quantity, label));
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public static global::System.Threading.Tasks.Task RaiseAsync(this global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent<Model.eventArgs> externalEvent, int quantity, string label)
        {
            return externalEvent.RaiseAsync(new Model.eventArgs(quantity, label));
        }
    }
}
