//HintName: Model.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

public partial class Model
{
    private global::Nice3point.Revit.Toolkit.External.IExternalEvent? _runEvent;

    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
    public global::Nice3point.Revit.Toolkit.External.IExternalEvent RunEvent => _runEvent ??= new global::Nice3point.Revit.Toolkit.External.ExternalEvent(new global::System.Action(Run));

    private global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent? _runAsyncEvent;

    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
    public global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent RunAsyncEvent => _runAsyncEvent ??= new global::Nice3point.Revit.Toolkit.External.AsyncExternalEvent(new global::System.Action(Run));
}
