//HintName: Consumer.Model`1.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Model<TValue>
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IExternalEvent<RunArgs> RunEvent => field ??= new global::Nice3point.Revit.Toolkit.External.ExternalEvent<RunArgs>((args) => Run(args.Value, args.Quantity));

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent<RunArgs> RunAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncExternalEvent<RunArgs>((args) => Run(args.Value, args.Quantity));

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public sealed record RunArgs(TValue Value, int Quantity);
    }

    public static partial class ModelExtensions
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public static global::Autodesk.Revit.UI.ExternalEventRequest Raise<TValue>(this global::Nice3point.Revit.Toolkit.External.IExternalEvent<Model<TValue>.RunArgs> externalEvent, TValue value, int quantity) where TValue : class, global::System.IDisposable, new()
        {
            return externalEvent.Raise(new Model<TValue>.RunArgs(value, quantity));
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public static global::System.Threading.Tasks.Task RaiseAsync<TValue>(this global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent<Model<TValue>.RunArgs> externalEvent, TValue value, int quantity) where TValue : class, global::System.IDisposable, new()
        {
            return externalEvent.RaiseAsync(new Model<TValue>.RunArgs(value, quantity));
        }
    }
}
