//HintName: Consumer.Outer.Model.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Outer
    {
        private partial class Model
        {
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
            public global::Nice3point.Revit.Toolkit.External.IExternalEvent<RunArgs> RunEvent => field ??= new global::Nice3point.Revit.Toolkit.External.ExternalEvent<RunArgs>((args) => Run(args.Quantity, args.Label));

            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
            public global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent<RunArgs> RunAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncExternalEvent<RunArgs>((args) => Run(args.Quantity, args.Label));

            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
            public sealed record RunArgs(int Quantity, string Label);
        }
    }
}
