//HintName: Consumer.Model.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial record struct Model
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IExternalEvent<RunArgs> RunEvent
        {
            get
            {
                if (field is not null)
                {
                    return field;
                }

                var handler = new global::System.Action<int, string>(Run);
                return field = new global::Nice3point.Revit.Toolkit.External.ExternalEvent<RunArgs>((args) => handler(args.Quantity, args.Label));
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent<RunArgs> RunAsyncEvent
        {
            get
            {
                if (field is not null)
                {
                    return field;
                }

                var handler = new global::System.Action<int, string>(Run);
                return field = new global::Nice3point.Revit.Toolkit.External.AsyncExternalEvent<RunArgs>((args) => handler(args.Quantity, args.Label));
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public sealed record RunArgs(int Quantity, string Label);
    }

    public static partial class ModelExtensions
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public static global::Autodesk.Revit.UI.ExternalEventRequest Raise(this global::Nice3point.Revit.Toolkit.External.IExternalEvent<Model.RunArgs> externalEvent, int quantity, string label)
        {
            return externalEvent.Raise(new Model.RunArgs(quantity, label));
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public static global::System.Threading.Tasks.Task RaiseAsync(this global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent<Model.RunArgs> externalEvent, int quantity, string label)
        {
            return externalEvent.RaiseAsync(new Model.RunArgs(quantity, label));
        }
    }
}
