//HintName: Consumer.Outer`1.Model`1.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Outer<TValue>
    {
        public partial class Model<TResult>
        {
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
            public global::Nice3point.Revit.Toolkit.External.IAsyncRequestExternalEvent<RunArgs, TResult> RunAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncRequestExternalEvent<RunArgs, TResult>((args) => Run(args.Value, args.Result));

            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
            public sealed record RunArgs(TValue Value, TResult Result);
        }
    }

    public static partial class OuterExtensions
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public static global::System.Threading.Tasks.Task<TResult> RaiseAsync<TValue, TResult>(this global::Nice3point.Revit.Toolkit.External.IAsyncRequestExternalEvent<Outer<TValue>.Model<TResult>.RunArgs, TResult> externalEvent, TValue value, TResult result) where TValue : class where TResult : struct
        {
            return externalEvent.RaiseAsync(new Outer<TValue>.Model<TResult>.RunArgs(value, result));
        }
    }
}
