//HintName: Consumer.Model`1.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Model<TValue>
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IAsyncRequestExternalEvent<TValue, TValue> RunAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncRequestExternalEvent<TValue, TValue>(new global::System.Func<TValue, TValue>(Run));
    }
}
