//HintName: Consumer.Model.Count.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Model
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IAsyncRequestExternalEvent<string, int> CountAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncRequestExternalEvent<string, int>(new global::System.Func<string, int>(Count));
    }
}
