//HintName: Consumer.Model.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Model
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IAsyncRequestExternalEvent<RunArgs, int> RunAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncRequestExternalEvent<RunArgs, int>((args) => Run(args.Quantity, args.Label));

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public sealed record RunArgs(int Quantity, string Label);
    }

    public static partial class ModelExtensions
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public static global::System.Threading.Tasks.Task<int> RaiseAsync(this global::Nice3point.Revit.Toolkit.External.IAsyncRequestExternalEvent<Model.RunArgs, int> externalEvent, int quantity, string label)
        {
            return externalEvent.RaiseAsync(new Model.RunArgs(quantity, label));
        }
    }
}
