//HintName: Consumer.Model.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Model
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IExternalEvent<int> RunEvent => field ??= new global::Nice3point.Revit.Toolkit.External.ExternalEvent<int>(new global::System.Action<int>(Run), global::Nice3point.Revit.Toolkit.External.ExternalEventOptions.AllowDirectInvocation);

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent<int> RunAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncExternalEvent<int>(new global::System.Action<int>(Run), global::Nice3point.Revit.Toolkit.External.ExternalEventOptions.AllowDirectInvocation);
    }
}
