//HintName: Consumer.Model.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Model
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IExternalEvent RunEvent => field ??= new global::Nice3point.Revit.Toolkit.External.ExternalEvent(new global::System.Action<global::Autodesk.Revit.UI.UIApplication>(Run));

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IAsyncExternalEvent RunAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncExternalEvent(new global::System.Action<global::Autodesk.Revit.UI.UIApplication>(Run));
    }
}
