//HintName: Consumer.Model.Run.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Consumer
{
    public partial class Model
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.CodeDom.Compiler.GeneratedCode("Nice3point.Revit.Toolkit.SourceGenerators.ExternalEventGenerator", "1.0.0.0")]
        public global::Nice3point.Revit.Toolkit.External.IAsyncRequestExternalEvent<int> RunAsyncEvent => field ??= new global::Nice3point.Revit.Toolkit.External.AsyncRequestExternalEvent<int>(new global::System.Func<int>(Run));
    }
}
