<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\Directory.Roslyn.props"/>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" VersionOverride="$(RoslynVersion).*" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" VersionOverride="$(RoslynVersion).*" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Nice3point.Revit.Toolkit.Analyzers\ExternalEvents\ExternalEventDiagnostics.cs"
                 Link="ExternalEvents\ExternalEventDiagnostics.cs"/>
    </ItemGroup>

</Project>